import type { NestFastifyApplication } from '@nestjs/platform-fastify';
import request from 'supertest';
import { bootstrapTestApp, requireSetCookie } from './helpers/bootstrap-test-app';

const describeE2e = process.env.SKIP_E2E === 'true' ? describe.skip : describe;

describeE2e('Artifacts (e2e)', () => {
  let app: NestFastifyApplication;

  beforeAll(async () => {
    app = await bootstrapTestApp();
  }, 30_000);

  afterAll(async () => {
    if (app) await app.close();
  });

  it('generates share-card artifact and retrieves metadata and content', async () => {
    const reportRes = await request(app.getHttpServer())
      .post('/api/v1/reports/fake')
      .send({ customFartName: 'Artifact Bean' })
      .expect(201);

    const reportId = String(reportRes.body.id);
    const cookies = requireSetCookie(reportRes);

    const artifactRes = await request(app.getHttpServer())
      .post(`/api/v1/reports/${reportId}/artifacts/share-card`)
      .set('Cookie', cookies)
      .send({ styleVariant: 'clinical' })
      .expect(201);

    expect(artifactRes.body.status).toBe('ready');
    expect(artifactRes.body.type).toBe('share_card');
    expect(artifactRes.body.storageKey).toMatch(/artifacts\/share_card\//);
    expect(artifactRes.body.contentUrl).toContain(artifactRes.body.id);

    const listRes = await request(app.getHttpServer())
      .get(`/api/v1/reports/${reportId}/artifacts`)
      .set('Cookie', cookies)
      .expect(200);

    expect(listRes.body.length).toBeGreaterThanOrEqual(1);
    expect(listRes.body[0].id).toBe(artifactRes.body.id);

    const contentRes = await request(app.getHttpServer())
      .get(`/api/v1/artifacts/${String(artifactRes.body.id)}/content`)
      .set('Cookie', cookies)
      .expect(200);

    expect(contentRes.text).toContain('Artifact Bean');
    expect(contentRes.text).toContain('Generated by Farts.com');
    expect(contentRes.headers['content-type']).toMatch(/text\/html/);
  });

  it('generates a PDF report artifact, dedupes per (reportId, themeCode), and streams %PDF- content', async () => {
    const reportRes = await request(app.getHttpServer())
      .post('/api/v1/reports/fake')
      .send({ customFartName: 'PDF Bean' })
      .expect(201);

    const reportId = String(reportRes.body.id);
    const cookies = requireSetCookie(reportRes);

    const first = await request(app.getHttpServer())
      .post(`/api/v1/reports/${reportId}/artifacts/pdf`)
      .set('Cookie', cookies)
      .send({ themeCode: 'clinical_gold' })
      .expect(201);

    expect(first.body.status).toBe('ready');
    expect(first.body.type).toBe('report_pdf');
    expect(first.body.themeCode).toBe('clinical_gold');
    expect(first.body.mimeType).toBe('application/pdf');
    expect(first.body.storageKey).toMatch(/^artifacts\/report_pdf\//);

    // Same (reportId, themeCode) returns the existing artifact (no re-render).
    const second = await request(app.getHttpServer())
      .post(`/api/v1/reports/${reportId}/artifacts/pdf`)
      .set('Cookie', cookies)
      .send({ themeCode: 'clinical_gold' })
      .expect(201);
    expect(second.body.id).toBe(first.body.id);

    // Different theme returns a new artifact.
    const third = await request(app.getHttpServer())
      .post(`/api/v1/reports/${reportId}/artifacts/pdf`)
      .set('Cookie', cookies)
      .send({ themeCode: 'default' })
      .expect(201);
    expect(third.body.id).not.toBe(first.body.id);
    expect(third.body.themeCode).toBe('default');

    // Unknown theme is coerced to default and reuses the default artifact.
    const fourth = await request(app.getHttpServer())
      .post(`/api/v1/reports/${reportId}/artifacts/pdf`)
      .set('Cookie', cookies)
      .send({ themeCode: 'does-not-exist' })
      .expect(201);
    expect(fourth.body.themeCode).toBe('default');
    expect(fourth.body.id).toBe(third.body.id);

    // Content stream returns the actual PDF bytes.
    const content = await request(app.getHttpServer())
      .get(`/api/v1/artifacts/${String(first.body.id)}/content`)
      .set('Cookie', cookies)
      .buffer(true)
      .parse((res, callback) => {
        const chunks: Buffer[] = [];
        res.on('data', (chunk: Buffer) => chunks.push(chunk));
        res.on('end', () => callback(null, Buffer.concat(chunks)));
      })
      .expect(200);
    expect(content.headers['content-type']).toMatch(/application\/pdf/);
    const body = content.body as Buffer;
    expect(body.subarray(0, 5).toString('ascii')).toBe('%PDF-');
  });
});
