import type { NestFastifyApplication } from '@nestjs/platform-fastify';
import request from 'supertest';
import { bootstrapTestApp, requireSetCookie } from './helpers/bootstrap-test-app';

const describeE2e = process.env.SKIP_E2E === 'true' ? describe.skip : describe;

describeE2e('Artifacts (e2e)', () => {
  let app: NestFastifyApplication;

  beforeAll(async () => {
    app = await bootstrapTestApp();
  }, 30_000);

  afterAll(async () => {
    if (app) await app.close();
  });

  it('generates share-card artifact and retrieves metadata and content', async () => {
    const reportRes = await request(app.getHttpServer())
      .post('/api/v1/reports/fake')
      .send({ customFartName: 'Artifact Bean' })
      .expect(201);

    const reportId = String(reportRes.body.id);
    const cookies = requireSetCookie(reportRes);

    const artifactRes = await request(app.getHttpServer())
      .post(`/api/v1/reports/${reportId}/artifacts/share-card`)
      .set('Cookie', cookies)
      .send({ styleVariant: 'clinical' })
      .expect(201);

    expect(artifactRes.body.status).toBe('ready');
    expect(artifactRes.body.type).toBe('share_card');
    expect(artifactRes.body.storageKey).toMatch(/artifacts\/share_card\//);
    expect(artifactRes.body.contentUrl).toContain(artifactRes.body.id);

    const listRes = await request(app.getHttpServer())
      .get(`/api/v1/reports/${reportId}/artifacts`)
      .set('Cookie', cookies)
      .expect(200);

    expect(listRes.body.length).toBeGreaterThanOrEqual(1);
    expect(listRes.body[0].id).toBe(artifactRes.body.id);

    const contentRes = await request(app.getHttpServer())
      .get(`/api/v1/artifacts/${String(artifactRes.body.id)}/content`)
      .set('Cookie', cookies)
      .expect(200);

    expect(contentRes.text).toContain('Artifact Bean');
    expect(contentRes.text).toContain('Generated by Farts.com');
    expect(contentRes.headers['content-type']).toMatch(/text\/html/);
  });
});
