import type { Report } from '../../../shared/domain/models';
import { ShareCardStyleVariant } from '../../../shared/domain/types';

export interface ShareCardRenderPayload {
  reportId: string;
  fartName: string;
  classification: string;
  powerScore: number;
  durationMs: number;
  emotionalTone: string;
  probableCause: string;
  cinematicParallel: string;
  threatLevel: string;
  fartHash: string;
  watermark: string;
  styleVariant: ShareCardStyleVariant;
  generatedAt: string;
}

export function buildShareCardPayload(
  report: Report,
  styleVariant: ShareCardStyleVariant = ShareCardStyleVariant.DEFAULT,
): ShareCardRenderPayload {
  return {
    reportId: report.id,
    fartName: report.fartName,
    classification: report.classification,
    powerScore: report.powerScore,
    durationMs: report.durationMs,
    emotionalTone: report.emotionalTone,
    probableCause: report.probableCause,
    cinematicParallel: report.cinematicParallel,
    threatLevel: report.threatLevel,
    fartHash: report.fartHash,
    watermark: 'Generated by Farts.com',
    styleVariant,
    generatedAt: report.completedAt ?? report.createdAt,
  };
}
