import { ShareCardStyleVariant } from '../../../shared/domain/types';
import { buildShareCardPayload } from './share-card-payload';
import { renderShareCardHtml } from './share-card-html.renderer';
import type { Report } from '../../../shared/domain/models';
import { ReportSource, ReportStatus } from '../../../shared/domain/types';

const sampleReport: Report = {
  id: '11111111-1111-4111-8111-111111111111',
  status: ReportStatus.COMPLETED,
  source: ReportSource.FAKE,
  fartName: 'Test Bean',
  classification: 'Silent Assassin',
  powerScore: 72,
  durationMs: 1200,
  emotionalTone: 'Wistful defiance',
  probableCause: 'Questionable chili',
  cinematicParallel: 'Submarine thriller',
  threatLevel: 'Amber',
  fartHash: 'fart_abc123',
  createdAt: '2026-05-17T12:00:00.000Z',
  updatedAt: '2026-05-17T12:00:00.000Z',
  completedAt: '2026-05-17T12:00:00.000Z',
};

describe('renderShareCardHtml', () => {
  it('includes report fields and watermark', () => {
    const payload = buildShareCardPayload(sampleReport, ShareCardStyleVariant.CLINICAL);
    const html = renderShareCardHtml(payload);

    expect(html).toContain('Test Bean');
    expect(html).toContain('Silent Assassin');
    expect(html).toContain('72 / 100');
    expect(html).toContain('Wistful defiance');
    expect(html).toContain('fart_abc123');
    expect(html).toContain('Generated by Farts.com');
    expect(html).not.toContain('motion.div');
  });

  it('is deterministic for the same payload', () => {
    const payload = buildShareCardPayload(sampleReport);
    expect(renderShareCardHtml(payload)).toBe(renderShareCardHtml(payload));
  });
});
