/**
 * Allowlist for browser-originated analytics (`frontend/src/lib/analytics-events.ts`).
 * Keep in sync when adding events; mismatches return 400 on ingest.
 */
export const CLIENT_ANALYTICS_EVENT_NAMES = [
  'landing_view',
  'landing_cta_click',
  'analyze_view',
  'intake_path_selected',
  'capture_started',
  'capture_completed',
  'capture_restarted',
  'capture_cancelled',
  'analysis_started',
  'analysis_completed',
  'report_view',
  'variant_switched',
  'caption_copied',
  'generate_another_clicked',
  'save_share_card_clicked',
  'share_view',
  'share_download_started',
  'share_download_succeeded',
  'share_download_failed',
  'open_full_dossier_clicked',
  'challenge_link_created',
  'challenge_link_opened',
  'challenge_cta_clicked',
  'challenge_context_forwarded',
  'premium_view',
  'premium_offer_viewed',
  'premium_cta_clicked',
  'premium_offer_selected',
  'premium_preview_interacted',
  'premium_back_to_report_clicked',
  'launch_view',
  'waitlist_cta_clicked',
  'early_access_requested',
  'waitlist_submitted',
  'sample_report_opened',
  'founding_badge_interacted',
  'release_notice_viewed',
  'press_view',
  'press_asset_opened',
  'press_quote_copied',
  'press_fact_sheet_interacted',
  'press_contact_clicked',
  'embargo_notice_viewed',
  'seed_tool_view',
  'seed_target_configured',
  'seed_variant_adjusted',
  'seed_output_selected',
  'seed_link_generated',
  'seed_link_copied',
  'seed_preview_opened',
  'methane_index_view',
  'classification_row_opened',
  'featured_artifact_opened',
  'ritual_teaser_interacted',
  'commentary_section_viewed',
  'fart_wrapped_view',
  'wrapped_story_panel_viewed',
  'wrapped_badge_interacted',
  'wrapped_share_opened',
  'wrapped_poster_copied',
  'wrapped_classification_opened',
  'ops_view',
  'ops_window_changed',
  'ops_variant_drilldown_opened',
  'reduced_motion_detected',
  'theme_toggled',
] as const;

const NAME_SET = new Set<string>(CLIENT_ANALYTICS_EVENT_NAMES);

export function isClientAnalyticsEventName(name: string): boolean {
  return NAME_SET.has(name);
}
